apiVersion: apps/v1
kind: Deployment
metadata:
  name: neureality
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: pythonapp
        image: giladt2789/neureality
        ports:
        - containerPort: 8182
---
apiVersion: v1
kind: Service
metadata:
  name: neureality-service
spec:
  type: NodePort
  selector:
    app: python
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8182
      nodePort: 31590
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: neureality-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: ingress-nginx
  rules:
  - http:
      paths:
      - path: /reverse
        pathType: Prefix
        backend:
          service:
            name: neureality-service
            port:
              number: 80
