---

- hosts: "K8S_Master, K8S_Node"
  become: yes
  vars_prompt:
   - name: "new_user"
     prompt: "Account need to be create in remote server."
     private: no
  roles:
    - create_user

- hosts: "K8S_Master, K8S_Node"
  remote_user: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
  roles:
    - K8S_install

- hosts: "K8S_Master"
  become: yes
  roles:
    - K8S_cluster_init

- hosts: "K8S_Node"
  become: yes
  gather_facts: yes
  roles:
    - K8S_join_worker_nodes

...